In [2]:
import torch
import numpy as np

import os
from definitions import LOG_DIR
from torch.utils.tensorboard import SummaryWriter

import gym
from gym.logger import ERROR

from src.agent import Agent
from src.simulation import simulate
from src.ornstein_uhlenbeck_process import OrnsteinUhlenbeckProcess

from matplotlib import pyplot as plt
from src.actor import Actor
import copy

In [3]:
writer = SummaryWriter(LOG_DIR)

In [4]:
gym.logger.set_level(ERROR)

In [5]:
env = gym.make("LunarLanderContinuous-v2")
agent = Agent(
    device="cuda",
    state_dim=env.observation_space.shape[0],
    action_dim=env.action_space.shape[0],
    actor_layer_sizes=[256, 128],
    critic_layer_sizes=[256, 128],
    replay_buffer_max_size=1e6,
    batch_size=128,
    learning_freq=1,
    γ=0.995,
    μ_θ_α=1e-4,
    Q_Φ_α=1e-3,
    ρ=0.95,
    noise_sigma=0.2,
    train_after=64,
    exploration=True,
    writer=writer,
    train_steps_per_update=1
)

In [10]:
# env.close()

In [6]:
# agent.exploration = False

In [ ]:
simulate(env, agent, episodes=400, max_episode_steps=1000, render=False)

In [13]:
i = 0
for sarsd in agent.Ɗ:
    state, action, reward, next_state, d = sarsd
    print(state)
    i += 1
    if i >= 100:
        break

tensor([[-0.0516,  0.5791, -0.1284,  ...,  0.0382,  0.0000,  0.0000],
        [-0.5313,  0.5077, -1.0374,  ...,  0.4587,  0.0000,  0.0000],
        [ 0.6405,  0.5209,  0.9193,  ..., -0.1206,  0.0000,  0.0000],
        ...,
        [-0.0446,  1.2230, -0.0242,  ..., -0.5467,  0.0000,  0.0000],
        [ 0.5790,  0.7828,  0.7587,  ...,  0.0290,  0.0000,  0.0000],
        [-0.8764,  1.4154, -1.0368,  ...,  0.1728,  0.0000,  0.0000]])
tensor([[ 0.6871,  0.5950,  1.3466,  ..., -0.4746,  0.0000,  0.0000],
        [ 0.3646,  0.6829,  0.6872,  ..., -0.5531,  0.0000,  0.0000],
        [-0.2944,  1.2462, -0.8080,  ...,  0.1003,  0.0000,  0.0000],
        ...,
        [-0.1669,  0.8173, -0.1803,  ..., -0.0554,  0.0000,  0.0000],
        [-0.0030,  1.4044, -0.3053,  ...,  0.0692,  0.0000,  0.0000],
        [-0.1940,  0.9882, -0.6952,  ...,  0.1290,  0.0000,  0.0000]])
tensor([[ 0.1445,  0.0060, -0.1304,  ...,  0.1491,  1.0000,  0.0000],
        [-0.0154,  0.7679, -0.1783,  ...,  0.2628,  0.0000,  0